version: 2
models:
- name: ddl_script_executions
  description: ''
  columns:
  - name: script_id
    data_type: string
    description: ''
  - name: script_name
    data_type: string
    description: ''
  - name: execution_status
    data_type: string
    description: ''
  - name: update_date
    data_type: timestamp
    description: ''
- name: dim_Cities
  description: 'This is the dimension table for cities.'
  columns:
  - name: CityID
    data_type: int
    description: ''
  - name: CityName
    data_type: string
    description: ''
  - name: StateProvinceID
    data_type: int
    description: ''
  - name: LatestRecordedPopulation
    data_type: int
    description: ''
  - name: LastEditedBy
    data_type: string
    description: ''
  - name: ValidFrom
    data_type: timestamp
    description: ''
  - name: ValidTo
    data_type: timestamp
    description: ''
- name: dim_departments
  description: ''
  columns:
  - name: DepartmentID
    data_type: int
    description: ''
  - name: Name
    data_type: string
    description: ''
  - name: GroupName
    data_type: string
    description: ''
  - name: ModifiedDate
    data_type: timestamp
    description: ''
- name: dim_products
  description: ''
  columns:
  - name: ProductID
    data_type: int
    description: ''
  - name: Name
    data_type: string
    description: ''
  - name: ProductNumber
    data_type: string
    description: ''
  - name: MakeFlag
    data_type: boolean
    description: ''
  - name: FinishedGoodsFlag
    data_type: boolean
    description: ''
  - name: Color
    data_type: string
    description: ''
  - name: SafetyStockLevel
    data_type: int
    description: ''
  - name: ReorderPoint
    data_type: int
    description: ''
  - name: StandardCost
    data_type: float
    description: ''
  - name: ListPrice
    data_type: float
    description: ''
  - name: Size
    data_type: string
    description: ''
  - name: SizeUnitMeasureCode
    data_type: string
    description: ''
  - name: WeightUnitMeasureCode
    data_type: string
    description: ''
  - name: Weight
    data_type: float
    description: ''
  - name: DaysToManufacture
    data_type: int
    description: ''
  - name: ProductLine
    data_type: string
    description: ''
  - name: Class
    data_type: string
    description: ''
  - name: Style
    data_type: string
    description: ''
  - name: ProductSubcategoryID
    data_type: int
    description: ''
  - name: ProductModelID
    data_type: int
    description: ''
  - name: SellStartDate
    data_type: timestamp
    description: ''
  - name: SellEndDate
    data_type: timestamp
    description: ''
  - name: DiscontinuedDate
    data_type: string
    description: ''
  - name: rowguid
    data_type: string
    description: ''
  - name: ModifiedDate
    data_type: timestamp
    description: ''
- name: order_territory
  description: ''
  columns:
  - name: SalesOrderID
    data_type: int
    description: ''
  - name: TerritoryID
    data_type: int
    description: ''
  - name: TerritoryName
    data_type: string
    description: ''
  - name: TerritoryGroup
    data_type: string
    description: ''
  - name: TaxAmt
    data_type: float
    description: ''
  - name: Freight
    data_type: float
    description: ''
  - name: TotalDue
    data_type: float
    description: ''
  - name: Comment
    data_type: string
    description: ''
  - name: ModifiedDate
    data_type: timestamp
    description: ''
- name: dim_territories
  description: 'gold layer table for territories'
  columns:
  - name: TerritoryID
    data_type: int
    description: 'Unique identifier for the territory'
  - name: Name
    data_type: string
    description: 'territory name'
  - name: CountryRegionCode
    data_type: string
    description: ''
  - name: Group
    data_type: string
    description: ''
  - name: SalesYTD
    data_type: float
    description: ''
  - name: SalesLastYear
    data_type: float
    description: ''
  - name: CostYTD
    data_type: int
    description: ''
  - name: CostLastYear
    data_type: int
    description: ''
  - name: rowguid
    data_type: string
    description: ''
  - name: ModifiedDate
    data_type: timestamp
    description: ''

- name: order_territory1
  description: ''
  columns:
  - name: order_sk
    data_type: string
    description: ''
  - name: SalesOrderID
    data_type: int
    description: ''
  - name: TerritoryID
    data_type: int
    description: ''
  - name: TerritoryName
    data_type: string
    description: ''
  - name: TerritoryGroup
    data_type: string
    description: ''
  - name: TaxAmt
    data_type: float
    description: ''
  - name: Freight
    data_type: float
    description: ''
  - name: TotalDue
    data_type: float
    description: ''
  - name: Comment
    data_type: string
    description: ''
  - name: ModifiedDate
    data_type: timestamp
    description: ''